proj/proj/apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
]

proj/proj/apps/projects/urls.py
from django.urls import path
from . import views
from .views import ListView, CreateView, UpdateView

app_name = 'projects'

urlpatterns = [
    path('', views.home, name='home'),
    path('list/', views.ProjectListView.as_view(), name='projects'),
    path('create/', views.ProjectCreateView.as_view(), name='project_create'),
    path('<int:pk>/edit', views.ProjectUpdateView.as_view(), name='project_edit'),
]

proj/proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('projects.urls')),
]

proj/proj/apps/accounts/models.py
from django.db import models

# Create your models here.

proj/proj/apps/projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    tag = models.CharField('Код', max_length=100)

    def __str__(self) -> str:
        return self.tag
    
    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

proj/proj/apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class CustomAuthernticationForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Имя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))

proj/proj/apps/projects/forms.py
from django import forms
from .models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'

        

proj/proj/apps/accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomAuthernticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def login_view(request):
    if request.method == 'POST':
        form = CustomAuthernticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('projects:home')
    else:
        form = CustomAuthernticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('accounts:login')

def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password2']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('projects:home')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/register.html', {'form': form})

proj/proj/apps/projects/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, UpdateView, CreateView
from django.urls import reverse_lazy
from .models import Project
from .forms import ProjectForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
@login_required
def home(request):
    return render(request, 'projects/home.html')
    
class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = 'projects/project_list.html'
    context_object_name = 'projects'

class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    form_class = ProjectForm
    template_name = 'projects/project_form.html'
    success_url = reverse_lazy('projects:projects')

class ProjectUpdateView(LoginRequiredMixin, UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = 'projects/project_form.html'
    success_url = reverse_lazy('projects:projects')

proj/proj/apps/accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Вход</title>
    <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
</head>
<body>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Вход">
        <a href="{% url 'accounts:register' %}">Регистрация</a>
    </form>
    
</body>
</html>

proj/proj/apps/accounts/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
</head>
<body>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Зарегистрироваться">
    </form>
    
</body>
</html>

proj/proj/apps/projects/templates/projects/home.html
{% extends 'base.html' %}

{% block  title %} Добро пожаловать {% endblock %}

{% block content %}

<h3> Привет, {{user.username}}! </h3>

{% endblock %}

proj/proj/apps/projects/templates/projects/project_form.html
{% extends 'base.html' %}

{% block  title %} Добро пожаловать {% endblock %}

{% block content %}

    <h1> {{view.object.pk|default:'Create'}} Project </h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Сохранить">
    </form>

{% endblock %}

proj/proj/apps/projects/templates/projects/project_list.html
{% extends 'base.html' %}

{% block  title %} Добро пожаловать {% endblock %}

{% block content %}


<h1>Список проктов</h1>

<ul>
    {% for project in projects %}
        <li> {{project.tag}} - <a href="{% url 'projects:project_edit' project.pk %}"> Редактировать</a> </li>
    {% endfor %}
</ul>
    <a href="{% url 'projects:project_create' %}">Создать новый</a>
{% endblock %}

proj/proj/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} {% endblock %} </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar" >
        <ul>
            <li><a href="{% url 'projects:home' %}">Домой</a></li>
            <li><a href="{% url 'projects:projects' %}">Проекты</a></li>
            <li><a href="{% url 'accounts:logout' %}">Выход</a></li>
        </ul>
    </nav>
    
    <div class="content" >

        {% block content %}

        {% endblock %}
    </div>


    <footer class="footer">
        &copy; Раиль Рафиков
    </footer>

</body>
</html>